CREATE TABLE `account` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `uid` BIGINT(20) UNSIGNED NOT NULL,
  `code` BIGINT(20) UNSIGNED NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `type` TINYINT(3) UNSIGNED NOT NULL,
  `parent_id` BIGINT(20) UNSIGNED DEFAULT NULL,
  `balance` BIGINT(20) DEFAULT 0,
  `deleted` TINYINT(1) DEFAULT 0,
  `created_by` BIGINT(20) UNSIGNED NOT NULL,
  `created_on` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` BIGINT(20) UNSIGNED NOT NULL,
  `updated_on` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

  PRIMARY KEY (`id`),
  UNIQUE INDEX `account_code` (`code`),
  UNIQUE INDEX `account_name` (`name`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;


CREATE TABLE `transaction` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `uid` BIGINT(20) UNSIGNED NOT NULL,
  `code` BIGINT(20) UNSIGNED NOT NULL,
  `type` TINYINT(3) UNSIGNED NOT NULL,
  `description` VARCHAR(128) DEFAULT NULL,
  `amount` BIGINT(20) NOT NULL,
  `deleted` TINYINT(1) DEFAULT 0,
  `created_by` BIGINT(20) UNSIGNED NOT NULL,
  `created_on` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` BIGINT(20) UNSIGNED NOT NULL,
  `updated_on` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

  PRIMARY KEY (`id`),
  UNIQUE INDEX `trans_code` (`code`),
) ENGINE=INNODB DEFAULT CHARSET=utf8;


CREATE TABLE `ledger` (
	`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`uid` BIGINT(20) UNSIGNED NOT NULL,
	`tx_id` BIGINT(20) UNSIGNED NOT NULL,
	`debit` BIGINT(20) DEFAULT 0,
	`credit` BIGINT(20) DEFAULT 0,
	`balance` BIGINT(20) NOT NULL,
	`cleared` TINYINT(1) UNSIGNED DEFAULT 0,
	`cleared_on` TIMESTAMP(3) DEFAULT 0,

	`deleted` TINYINT(1) DEFAULT 0,
  `created_by` BIGINT(20) UNSIGNED NOT NULL,
  `created_on` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` BIGINT(20) UNSIGNED NOT NULL,
  `updated_on` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;


CREATE TABLE `contact` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) DEFAULT NULL,
  `mobile` VARCHAR(32) DEFAULT NULL,
  `qq` VARCHAR(32) DEFAULT NULL,
  `address` VARCHAR(256) DEFAULT NULL,
  `deleted` TINYINT(1) DEFAULT 0,
  `created_by` BIGINT(20) UNSIGNED NOT NULL,
  `created_on` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3),
  `updated_by` BIGINT(20) UNSIGNED NOT NULL,
  `updated_on` TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP(3) ,

  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;
